### ISSUE TITLE
[Issue] Quest with crafting items is performed only while holding down the shift key

### ISSUE THREAD

**Issue by JaycobYT** [GC-spigot/battle-pass#262]
**Describe the bug**
Created a quest in which you need to craft items (chests). I noticed a problem: the progress of the quest is counted only when the shift key is held down. If you craft items in a workbench and simply transfer them to your inventory, then progress is not counted.

**To Reproduce**
Create a quest:
type: craft
variable: chest:0
required-progress: 16

**Screenshots / Video**
Video demonstrating the bug from a player on my server (Uploaded to file sharing. You can see it there): https://fex.net/ru/s/rdpasom

**Server Information:**
- Server Version: Purpur 1.18.2 (last build)
- Plugin Version: 3.14.0

**Comment by RSLuke** [comment]
Same issue here confirmed, happens for any material

**Comment by GC-spigot** [comment]
Fixed!

**Comment by RSLuke** [comment]
> Fixed!

Fixed in an upcoming release ?

**Comment by GC-spigot** [comment]
Yes

**Comment by RSLuke** [comment]
It isn't fixed, now what works is to craft several items at once and put them in the inventory, but if you do only one item it doesn't count
