### ISSUE TITLE
Plotsquared & BuildBattle Errors

### ISSUE THREAD

**Issue by SirCraftypants** [GC-spigot/battle-pass#27]
**Describe the bug**

https://paste.helpch.at/aqaqirasiw.md

**Server Information (please complete the following information):**
- Server Version: PaperSpigot-#580 1.16.5
- Plugin Version: 3.21.2

Update: just updated to Battlepass 3.23 and the errors persist.

**Comment by SirCraftypants** [comment]
Any idea when these with be updated?

**Comment by GC-spigot** [comment]
These are actually for buildbattle and plotsquared, will look into it for next update

**Comment by GC-spigot** [comment]
Try updating both plugins, I don't see any issues with them, but this says that some api things are missing from those plugins. What version of them are you running?

**Comment by SirCraftypants** [comment]
Currently 

AdvancedEnchantments-8.0.2
PlotSquared-Bukkit-5.13.11-Premium

I will see if i need to update now.

**Comment by SirCraftypants** [comment]
OK plotsquared is currently up to date.

I was waiting for you to verify my advanced enchantments purchase on my account on your website as i purchased advanced enchantments on spigotmc before you setup your website and my battlepass purchase from your website. I will update it from spigotmc for now and see what happens but, the latest plotsquared is throwing it's error with the latest version on paper 1.16.5

**Comment by SirCraftypants** [comment]
OK Advanced Enchantments is no longer throwing it's Error but now Buildbattle as well as Plotsquared are both throwing Errors

https://paste.helpch.at/zaporigele.cpp

PlotSquared-Bukkit-5.13.11-Premium
buildbattle-4.5.0

as you can see both plugins are up to date?

Checked Battlepass also 

BattlePass-3.24

**Comment by SirCraftypants** [comment]
Oh I'm also on Java 11
Paper 1.1.6.5

**Comment by GC-spigot** [comment]
There are 0 errors from AdvancedEnchantments, it’s only from those 2 i listed. Other messages are indication that for example, AE, works fine

**Comment by SirCraftypants** [comment]
> 
> There are 0 errors from AdvancedEnchantments, it’s only from those 2 i listed. Other messages are indication that for example, AE, works fine
> […](#)
> On 2021-05-07, at 01:31 PM, SirCraftypants ***@***.***> wrote: ﻿ Oh I'm also on Java 11 Paper 1.16.5 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

yeah my mistake, i was half a sleep when i posted it, i meant plotsquared and battlepass.

**Comment by SirCraftypants** [comment]
Not sure it the latest update has anything to do with this issue but, i've updated to 3.25 and the errors persist.

**Comment by SirCraftypants** [comment]
> 
> 
> These are actually for buildbattle and plotsquared, will look into it for next update

there's been at least 2 updates since i reported these with no fix in sight?

**Comment by SirCraftypants** [comment]
On top of the two present errors there's also a warn with the latest version 

[10:50:05 WARN]: [BattlePass] "BattlePass v3.31" has registered a listener for n3kas.ae.api.EnchantApplyEvent on method "public void io.github.battlepass.quests.quests.external.AdvancedEnchantmentsQuests.onCustomEnchantApply(n3kas.ae.api.EnchantApplyEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [].

Really appreciate if you fixed it all as i should have launched my server 2 weeks ago but still waiting for your's and another Devs plugin to be fixed.

**Comment by GC-spigot** [comment]
Should be resolved

**Comment by SirCraftypants** [comment]
BattlePass] Plugin BattlePass v3.31 has failed to register events for class io.github.battlepass.quests.quests.external.PlotSquaredQuests because com/github/intellectualsites/plotsquared/bukkit/events/PlayerClaimPlotEvent does not exist.

Still persists in 1.17

**Comment by SirCraftypants** [comment]
Here's the latest error im getting with battlepass 3.39

[01:50:04 ERROR]: [BattlePass] BattlePass v3.39 attempted to register an invalid EventHandler method signature "public void io.github.battlepass.quests.quests.external.PlotSquaredQuests.onPlotTrust(com.plotsquared.core.events.PlayerPlotTrustedEvent)" in class io.github.battlepass.quests.quests.external.PlotSquaredQuests
[01:50:04 ERROR]: [BattlePass] BattlePass v3.39 attempted to register an invalid EventHandler method signature "public void io.github.battlepass.quests.quests.external.PlotSquaredQuests.onTeleportToPlot(com.plotsquared.core.events.PlayerTeleportToPlotEvent)" in class io.github.battlepass.quests.quests.external.PlotSquaredQuests
[01:50:04 ERROR]: [BattlePass] BattlePass v3.39 attempted to register an invalid EventHandler method signature "public void io.github.battlepass.quests.quests.external.PlotSquaredQuests.onPlotEnter(com.plotsquared.core.events.PlayerEnterPlotEvent)" in class io.github.battlepass.quests.quests.external.PlotSquaredQuests
[01:50:04 ERROR]: [BattlePass] BattlePass v3.39 attempted to register an invalid EventHandler method signature "public void io.github.battlepass.quests.quests.external.PlotSquaredQuests.onPlotClaim(com.plotsquared.core.events.PlayerClaimPlotEvent)" in class io.github.battlepass.quests.quests.external.PlotSquaredQuests
[01:50:04 ERROR]: [BattlePass] BattlePass v3.39 attempted to register an invalid EventHandler method signature "public void io.github.battlepass.quests.quests.external.PlotSquaredQuests.onPlotRate(com.plotsquared.core.events.PlotRateEvent)" in class io.github.battlepass.quests.quests.external.PlotSquaredQuests

**Comment by SirCraftypants** [comment]
Sorry i forgot to add, this is now on 1.17 #55 java 16

**Comment by SirCraftypants** [comment]
Error still present on Paper 1.17 #69 Java 16

**Comment by GC-spigot** [comment]
What version of plotsquared are you using?

**Comment by SirCraftypants** [comment]
> 
> What version of plotsquared are you using?
> […](#)
> On 2021-07-03, at 10:58 AM, SirCraftypants ***@***.***> wrote: ﻿ Error still present on Paper 1.17 #69 Java 16 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

PlaceholderAPI-2.10.10-DEV-124
